import assert from 'node:assert/strict';
import path from 'node:path';

export async function verifyBrowserQueue({context,extensionId,until,checks,work,fixture,setGate}) {
  const started=[],releases=new Map();
  setGate(url=>{const id=url.pathname.match(/synthetic-image-(20[1-3])\.png$/)?.[1];if(!id)return Promise.resolve();started.push(id);return new Promise(resolve=>releases.set(id,resolve));});
  const page=await context.newPage();await page.setViewportSize({width:1440,height:1000});await page.goto('https://x.com/synthetic/status/201');
  const action=page.locator('[data-locus-action] button');
  const changePost=async id=>{await page.evaluate(html=>{const next=new DOMParser().parseFromString(html,'text/html').querySelector('article');document.querySelector('article')?.replaceWith(next);window.installFixtureArticle(next);},fixture(id));await until(()=>page.locator('article').getByText('Synthetic post '+id,{exact:false}).count(),Boolean,'new visible source');await action.waitFor();};
  const enqueue=async()=>{await action.click({modifiers:["Shift"]});await page.getByRole('button',{name:'Add to queue · 2 media',exact:true}).waitFor();await page.getByRole('checkbox').last().uncheck();await page.getByRole('button',{name:'Add to queue · 1 media',exact:true}).click();await page.getByRole('button',{name:'Expand capture queue',exact:true}).waitFor();};
  try {
    await enqueue();await until(()=>started.length,value=>value===1,'first actual media request blocked');await changePost('202');await enqueue();await until(()=>started.length,value=>value===2,'second actual media request blocked');await changePost('203');await enqueue();assert.deepEqual(started,['201','202']);
    await page.getByRole('button',{name:'Expand capture queue',exact:true}).click();await until(()=>page.locator('[data-task-id]').count(),count=>count===3,'three accepted task rows');const third=page.locator('[data-task-id]').filter({hasText:'@synthetic · 203'});await third.getByText('Queued',{exact:true}).waitFor();await third.getByText('Position 1',{exact:true}).waitFor();const ids=await page.locator('[data-task-id]').evaluateAll(rows=>rows.map(row=>row.dataset.taskId));const thirdId=await third.getAttribute('data-task-id');
    await page.screenshot({path:path.join(work,'capture-queue-active-wide.png')});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(work,'capture-queue-active-narrow.png')});await page.setViewportSize({width:1440,height:1000});
    await page.getByRole('button',{name:'Minimize capture queue',exact:true}).click();await page.screenshot({path:path.join(work,'capture-queue-bar.png')});await page.getByRole('button',{name:'Expand capture queue',exact:true}).click();
    await page.locator('article').evaluate(article=>article.remove());await until(()=>page.locator('[data-locus-action]').count(),count=>count===0,'virtualized article detached');assert.equal(await page.locator('[data-task-id]').count(),3,'Accepted task rows outlive the source DOM');await page.getByRole('button',{name:'Minimize capture queue',exact:true}).click();
    await page.reload();await page.getByRole('button',{name:'Expand capture queue',exact:true}).click();await until(()=>page.locator('[data-task-id]').count(),count=>count===3,'background queue restored after source reload');assert.deepEqual((await page.locator('[data-task-id]').evaluateAll(rows=>rows.map(row=>row.dataset.taskId))).sort(),ids.sort());
    const worker=context.serviceWorkers().find(worker=>worker.url().includes(extensionId));await worker.evaluate(()=>{globalThis.__queueWorkerMarker=true;});const cdp=await context.newCDPSession(page);await cdp.send('ServiceWorker.enable');await cdp.send('ServiceWorker.stopAllWorkers');await page.getByRole('button',{name:'Refresh status',exact:true}).click();await until(async()=>{const next=context.serviceWorkers().find(worker=>worker.url().includes(extensionId));return next?next.evaluate(()=>globalThis.__queueWorkerMarker!==true).catch(()=>false):false;},Boolean,'worker recreated with existing queue owner');assert.deepEqual(started,['201','202']);await cdp.detach();
    releases.get('201')();await until(()=>started.length,value=>value===3,'third FIFO job dispatched automatically after first release');assert.deepEqual(started,['201','202','203']);await until(()=>page.locator('[data-task-id="'+thirdId+'"]').getByText('Queued',{exact:true}).count(),count=>count===0,'queue position removed after dispatch');releases.get('202')();releases.get('203')();
    for(const id of ids)await page.locator('[data-task-id="'+id+'"]').getByText('Staged locally',{exact:true}).waitFor();await page.locator('[data-task-id="'+thirdId+'"]').getByRole('button',{name:'Open result',exact:true}).click();await until(async()=>context.pages().some(tab=>tab.url().endsWith('#'+thirdId)),Boolean,'explicit queue row opens its exact result');
    checks.push('Real FIFO queue: two blocked Blob requests plus a third waiting on one browsing page; task rows survive source detachment/reload and worker recreation; releasing one dispatches the third automatically, all retain, and exact result opening stays explicit');
  } finally {for(const release of releases.values())release();setGate(undefined);await page.close();}
}
