import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import { BilibiliLeases } from './bilibili-leases';
let alarm:unknown;let storage: Record<string, unknown>, rules: Map<number, unknown>, manager: BilibiliLeases;
const access = vi.fn<() => Promise<boolean>>(), live = vi.fn<(token: string, job: string) => Promise<boolean>>();
const url = 'https://synthetic.bilivideo.com/upgcxcode/1/2/123/123-1-64.m4s?private=x';
beforeEach(() => { alarm=undefined;storage = {}; rules = new Map(); access.mockReset().mockResolvedValue(true); live.mockReset().mockResolvedValue(true); vi.stubGlobal('chrome', { runtime: { id: 'fixture-extension' }, alarms: { get:vi.fn(async()=>alarm),create: vi.fn(async()=>{alarm={name:"owned"};}), clear: vi.fn(async()=>{alarm=undefined;}), onAlarm: { addListener: vi.fn() } }, storage: { session: { get: vi.fn(async () => structuredClone(storage)), set: vi.fn(async value => { storage = { ...storage, ...structuredClone(value) }; }) } }, declarativeNetRequest: { getSessionRules: vi.fn(async () => [...rules.values()]), updateSessionRules: vi.fn(async ({ addRules = [], removeRuleIds = [] }) => { for (const id of removeRuleIds) rules.delete(id); for (const rule of addRules) rules.set(rule.id, rule); }) } }); manager = new BilibiliLeases(access, live); });
afterEach(() => vi.unstubAllGlobals());
describe('Bilibili CDN lease ownership', () => {
  it('has no idle alarm, scopes exact URLs/initiator/GET, and removes only its own lease', async () => { await manager.reconcile(); expect(chrome.alarms.create).not.toHaveBeenCalled(); await manager.acquire('a', 'job-a', url, 'track', '123'); await manager.acquire('b', 'job-b', url + '&second=1', 'track', '123'); const rule = [...rules.values()][0] as chrome.declarativeNetRequest.Rule; expect(rule.condition.initiatorDomains).toEqual(['fixture-extension']); expect(rule.condition.requestDomains).toEqual(['synthetic.bilivideo.com']); expect(rule.condition.regexFilter).toMatch(/^\^.*\$$/); expect(rule.action.requestHeaders).toEqual([{ header: 'Referer', operation: 'set', value: 'https://www.bilibili.com/' }]); await manager.release('a'); expect(rules.size).toBe(1); await manager.release('a'); expect(rules.size).toBe(1); await manager.release('b'); expect(rules.size).toBe(0); expect(chrome.alarms.clear).toHaveBeenCalled(); });
  it('preserves surviving fetches on worker recreation but removes lost-owner rules', async () => { await manager.acquire('a', 'job-a', url, 'track', '123'); const next = new BilibiliLeases(access, live); await next.reconcile(); expect(rules.size).toBe(1);expect(chrome.alarms.create).toHaveBeenCalledTimes(1); live.mockResolvedValue(false); await next.reconcile(); expect(rules.size).toBe(0); });
  it('rejects revoked access and foreign paths and cleans owned rules after removal', async () => { await expect(manager.acquire('a', 'job-a', url, 'track', '456')).rejects.toThrow('CID'); await manager.acquire('b', 'job-b', url, 'track', '123'); access.mockRejectedValue(new Error('revoked')); await manager.reconcile(); expect(rules.size).toBe(0); await expect(manager.acquire('c', 'job-c', url, 'track', '123')).rejects.toThrow('revoked'); });
  it('retries failed cleanup without later traffic postponing its alarm or removing a new lease',async()=>{
    await manager.acquire('old','job-old',url,'track','123');vi.mocked(chrome.declarativeNetRequest.updateSessionRules).mockRejectedValueOnce(new Error('Temporary removal failure'));
    await expect(manager.release('old')).rejects.toThrow('removal');await manager.acquire('new','job-new',url+'&second=1','track','123');expect(chrome.alarms.create).toHaveBeenCalledTimes(1);
    live.mockImplementation(async token=>token==='new');await manager.reconcile();expect(rules.size).toBe(1);await manager.release('old');expect(rules.size).toBe(1);await manager.release('new');expect(rules.size).toBe(0);
  });
});
