// Identical, synthetic evidence for both comparison samples. Never imported by production.
export type Kind = 'setup' | 'failed' | 'unverified' | 'legacy' | 'partial' | 'retention' | 'active' | 'saved';
export type View = 'Inbox' | 'In progress' | 'Saved' | 'All captures';
export type Tone = 'outline' | 'success' | 'warning' | 'destructive' | 'info';
export type Outcome = { text: string; tone: Tone };
export type Sample = { id: Kind; site: string; label: string; url: string; age: string; author: string; handle: string; text: string; capture: Outcome; local: Outcome; locus: Outcome; hint: string; headline: string; reason: string; action?: string };
const good: Outcome = { text: 'Complete', tone: 'success' };
const retained: Outcome = { text: 'Retained', tone: 'outline' };
export const samples: Sample[] = [
  { id:'setup', site:'Twitter / X', label:'@fieldnotes · 1979876543210987654', url:'https://x.com/fieldnotes/status/1979876543210987654', age:'2m ago', author:'Avery Park', handle:'@fieldnotes', text:'A little room to slow down.\n\nKeeping this note from our morning walk: the layers of green, a quiet path, and the last light over the hills.\n\nSmall observations become useful when you can find them again.', capture:good, local:retained, locus:{text:'Setup required',tone:'info'}, hint:'Staged locally · configure Locus', headline:'Your capture is held locally.', reason:'Set up the Locus connection, then explicitly continue the original save. Configuration alone will not send this capture.', action:'Connection settings' },
  { id:'failed', site:'Bilibili', label:'BV1sampleA · P1 · A studio in the afternoon', url:'https://www.bilibili.com/video/BV1sampleA', age:'18m ago', author:'Studio North', handle:'Bilibili uploader', text:'An afternoon in the studio. A short study of light, sound and the objects we keep around us.\n\nThis synthetic example demonstrates a complete capture whose Locus save needs attention.', capture:good, local:retained, locus:{text:'Save failed',tone:'destructive'}, hint:'Save failed · inspect the original attempt', headline:'Locus could not finish the save.', reason:'The acquired content is retained locally. Review the original attempt before continuing; confirmed uploads must not be repeated.', action:'Review save options' },
  { id:'unverified', site:'Twitter / X', label:'@lenareed · 9001002', url:'https://x.com/lenareed/status/9001002', age:'42m ago', author:'Lena Reed', handle:'@lenareed', text:'Good interfaces make room for the thing you came to see.\n\nStart with the content. Keep the details close by. Let the tools get out of the way.', capture:good, local:retained, locus:{text:'Unverified',tone:'warning'}, hint:'Save unverified · check original request', headline:'The original save is not yet verified.', reason:'A response was lost. Inspect the existing request before deciding whether its unfinished work can continue.', action:'Review save options' },
  { id:'legacy', site:'Twitter / X', label:'@paperandform · 9001006', url:'https://x.com/paperandform/status/9001006', age:'1h ago', author:'Paper & Form', handle:'@paperandform', text:'A simple test for a reading space: is the content still the first thing you notice?', capture:good, local:retained, locus:{text:'No attempt',tone:'outline'}, hint:'Locally staged · available for export', headline:'Available for local inspection and export.', reason:'This older capture has no Locus save attempt. Keep its original content or export a local copy; no retroactive send action is implied.' },
  { id:'partial', site:'Twitter / X', label:'@studionorth · 1979876543210987668', url:'https://x.com/studionorth/status/1979876543210987668', age:'2h ago', author:'Studio North', handle:'@studionorth', text:'A few references for the next chapter of our field journal.\n\nThe message is here. One selected image could not be fetched.', capture:{text:'Partial',tone:'warning'}, local:retained, locus:{text:'Not sent',tone:'outline'}, hint:'Selected content missing · available portions kept', headline:'One selected file is missing.', reason:'Inspect the available content or export those portions. Incomplete captures are not sent to Locus.' },
  { id:'retention', site:'Twitter / X', label:'@noahellis · 9001004', url:'https://x.com/noahellis/status/9001004', age:'3h ago', author:'Noah Ellis', handle:'@noahellis', text:'Notes from today’s prototype review:\n\nPreserve the useful context. Make the next action clear. Keep the original details available.', capture:good, local:{text:'Not retained',tone:'destructive'}, locus:{text:'Saved',tone:'success'}, hint:'Local save failed · export available content', headline:'The current content is not retained locally.', reason:'Only a committed local revision is recoverable after restart. Export available content now if you need a local copy; the confirmed Locus save is a separate outcome.' },
  { id:'active', site:'Bilibili', label:'BV1sampleB · P2 · Notes from a quiet workshop', url:'https://www.bilibili.com/video/BV1sampleB?p=2', age:'Just now', author:'Quiet Workshop', handle:'Bilibili uploader', text:'Capture is still in progress. The file outcome is pending, not a terminal failure.', capture:{text:'Acquiring',tone:'info'}, local:{text:'Pending',tone:'info'}, locus:{text:'Not sent',tone:'outline'}, hint:'Acquiring selected content', headline:'The selected capture is still running.', reason:'Wait for the producer’s outcome. Closing the inspection view does not cancel accepted work.' },
  { id:'saved', site:'Twitter / X', label:'@fieldnotes · 9001005', url:'https://x.com/fieldnotes/status/9001005', age:'Yesterday', author:'Avery Park', handle:'@fieldnotes', text:'Small observations become useful when you can find them again.\n\nA few lines from the notebook, kept for later.', capture:good, local:retained, locus:{text:'Saved',tone:'success'}, hint:'Locus confirmed the complete import', headline:'Saved to Locus, with a local copy retained.', reason:'Inspect the content, export a local copy, or explicitly clear this extension’s retained copy.' },
];
export function belongs(sample:Sample, view:View) { return view==='All captures' || (view==='Saved' ? sample.id==='saved' : view==='In progress' ? sample.id==='active' : sample.id!=='saved' && sample.id!=='active'); }

export function readSamplePreset() {
  const params = new URLSearchParams(location.search);
  const scenario = ['empty', 'loading'].includes(params.get('scenario') ?? '') ? params.get('scenario')! : 'normal';
  const requested = samples.find(sample => sample.id === params.get('capture'));
  const view: View = requested?.id === 'saved' ? 'Saved' : requested?.id === 'active' ? 'In progress' : 'Inbox';
  const selected = scenario !== 'normal' ? null : requested?.id ?? (matchMedia('(min-width: 768px)').matches ? 'setup' : null);
  return { scenario, view, selected: selected as Kind | null };
}
