import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  ArchiveIcon, ArrowLeftIcon, ArrowUpRightIcon, CheckIcon, CircleAlertIcon,
  ClockIcon, DownloadIcon, FileIcon, InboxIcon, LayersIcon, ListIcon,
  MenuIcon, SearchIcon, SettingsIcon,
  ShieldCheckIcon, Trash2Icon, TriangleAlertIcon, XIcon,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription, EmptyMedia, EmptyContent } from '@/components/ui/empty';
import { Field, FieldGroup, FieldLabel, FieldDescription } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { InputGroup, InputGroupInput, InputGroupAddon, InputGroupButton } from '@/components/ui/input-group';
import { Skeleton } from '@/components/ui/skeleton';
import { samples, belongs, readSamplePreset, type Kind, type View, type Outcome, type Sample } from '../shared/sample-data';
import './styles.css';

const viewIcons = { Inbox:InboxIcon, 'In progress':ClockIcon, Saved:CheckIcon, 'All captures':ArchiveIcon };
function Status({ value }: { value:Outcome }) {
  const Icon = value.tone==='success' ? CheckIcon : value.tone==='destructive' ? CircleAlertIcon : value.tone==='warning' ? TriangleAlertIcon : value.tone==='info' ? ClockIcon : InboxIcon;
  return <Badge variant={value.tone}><Icon aria-hidden="true" data-icon="inline-start"/>{value.text}</Badge>;
}
function Outcomes({ sample }: { sample:Sample }) { return <dl className="outcome-strip" aria-label="Independent capture outcomes">{[['Capture',sample.capture],['Local copy',sample.local],['Locus save',sample.locus]].map(([label,value])=><div key={label as string}><dt>{label as string}</dt><dd><Status value={value as Outcome}/></dd></div>)}</dl>; }

function App() {
  const [page,setPage]=useState<string>('workspace');
  const [preset]=useState(readSamplePreset);
  const [view,setView]=useState<View>(preset.view);
  const [selected,setSelected]=useState<Kind|null>(preset.selected);
  const [tab,setTab]=useState<string>('preview');
  const [query,setQuery]=useState('');
  const [scenario,setScenario]=useState(preset.scenario);
  const [removed,setRemoved]=useState<Kind[]>([]);
  const [dialog,setDialog]=useState<'settings'|'queue'|'clear'|'navigation'|null>(null);
  const [notice,setNotice]=useState('');
  const backRef=useRef<HTMLButtonElement>(null);
  const searchRef=useRef<HTMLInputElement>(null);
  const rowsRef=useRef(new Map<string,HTMLButtonElement>());
  const focusIntent=useRef<'detail'|'list'|null>(null);
  const originRow=useRef<Kind|null>(null);
  useEffect(()=>{ if (focusIntent.current==='detail') backRef.current?.focus(); if(focusIntent.current==='list') (rowsRef.current.get(originRow.current??'')??searchRef.current)?.focus(); focusIntent.current=null; },[selected]);
  const records=scenario==='empty'?[]:samples.filter(item=>!removed.includes(item.id));
  const rows=records.filter(item=>belongs(item,view)&&`${item.label} ${item.url}`.toLowerCase().includes(query.toLowerCase().trim()));
  const sample=records.find(item=>item.id===selected);
  function select(id:Kind) { originRow.current=id; focusIntent.current=matchMedia('(max-width: 767px)').matches?'detail':null; setSelected(id); setTab('preview'); }
  function back() { focusIntent.current='list'; setSelected(null); }
  function changeView(next:View) { setView(next); setQuery(''); setSelected(null); setDialog(null); }
  function feedback(text:string) { setNotice(`Design sample: ${text}`); }
  function action() { if(sample?.id==='setup') setDialog('settings'); else setTab('activity'); }
  function navigation() { return <><div className="nav-items">{(Object.keys(viewIcons) as View[]).map(name=>{const Icon=viewIcons[name];return <Button key={name} variant={view===name?'secondary':'ghost'} onClick={()=>changeView(name)} aria-current={view===name?'page':undefined}><Icon aria-hidden="true" data-icon="inline-start"/>{name}<span className="nav-count">{records.filter(item=>belongs(item,name)).length}</span></Button>;})}</div><div className="navigation-footer"><Button variant="ghost" onClick={()=>setDialog('queue')}><LayersIcon aria-hidden="true" data-icon="inline-start"/>Task queue<span className="nav-count">1</span></Button><Button variant="ghost" onClick={()=>setDialog('settings')}><SettingsIcon aria-hidden="true" data-icon="inline-start"/>Settings</Button><div className="connection"><strong>Locus connection</strong>Not configured in this example</div></div></>; }
  return <>
    <header className="design-bar"><div className="design-identity"><strong>Signal shelf</strong><span>Interactive design sample · synthetic content</span></div><div className="design-controls"><Tabs value={page} onValueChange={value=>setPage(String(value))}><TabsList><TabsTrigger value="workspace">Inbox sample</TabsTrigger><TabsTrigger value="components">Component sheet</TabsTrigger></TabsList></Tabs>{page==='workspace'&&<label className="example-select">Example<select value={scenario} onChange={e=>{setScenario(e.target.value);setSelected(null);setRemoved([]);setQuery('');}}><option value="normal">All sample states</option><option value="empty">Empty library</option><option value="loading">Loading library</option></select></label>}</div></header>
    {page==='components'?<ComponentSheet onSettings={()=>setDialog('settings')} onQueue={()=>setDialog('queue')} onFeedback={feedback}/>:<main className="workspace" data-selected={!!sample}>
      <aside className="navigation" aria-label="Library navigation"><div className="brand"><LayersIcon aria-hidden="true"/><h1>Locus</h1></div><p className="navigation-caption">Web captures, kept together.</p>{navigation()}</aside>
      <section className="list-pane" aria-label="Capture list"><div className="list-header"><div className="list-title"><Button className="narrow-nav" variant="ghost" size="icon-lg" aria-label="Open navigation" onClick={()=>setDialog('navigation')}><MenuIcon/></Button><h2>{view}</h2><span>{scenario==='loading'?'Reading…':`${rows.length} captures`}</span></div><Field><FieldLabel className="sr-only" htmlFor="sample-search">Search capture label or source URL</FieldLabel><InputGroup><InputGroupInput id="sample-search" ref={searchRef} placeholder="Search label or source URL" value={query} onChange={e=>{setQuery(e.target.value);setSelected(null);}}/><InputGroupAddon><SearchIcon aria-hidden="true"/></InputGroupAddon>{query&&<InputGroupAddon align="inline-end"><InputGroupButton size="icon-sm" aria-label="Clear search" onClick={()=>setQuery('')}><XIcon/></InputGroupButton></InputGroupAddon>}</InputGroup></Field></div>
      {scenario==='loading'?<div className="loading-rows" role="status" aria-label="Loading captures">{[1,2,3,4].map(i=><div key={i} className="flex flex-col gap-3"><Skeleton className="h-3 w-28"/><Skeleton className="h-5 w-full"/><Skeleton className="h-3 w-40"/></div>)}</div>:rows.length?<ul className="capture-rows">{rows.map((item,index)=><li key={item.id}><button className="capture-row" ref={node=>{if(node)rowsRef.current.set(item.id,node);else rowsRef.current.delete(item.id);}} aria-label={`Open capture ${item.label}`} aria-pressed={selected===item.id} onClick={()=>select(item.id)} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?rows.length-1:Math.max(0,Math.min(rows.length-1,index+(e.key==='ArrowDown'?1:-1)));const nextRow=rows[next];if(nextRow)rowsRef.current.get(nextRow.id)?.focus();}}}><span className="row-top"><span>{item.site}</span><span>{item.age}</span></span><span className="row-label">{item.label}</span><span className="row-bottom"><Status value={item.id==='partial'?item.capture:item.id==='retention'?item.local:item.locus}/></span><span className="row-top">{item.hint}</span></button></li>)}</ul>:<Empty><EmptyHeader><EmptyMedia><InboxIcon aria-hidden="true"/></EmptyMedia><EmptyTitle>{query?'No matching captures':!records.length?'No captures yet':view==='Inbox'?'Your Inbox is clear':view==='Saved'?'No saved captures yet':view==='In progress'?'Nothing in progress':'No captures yet'}</EmptyTitle><EmptyDescription>{query?'Search matches the capture label and source URL. Try an ID or a label fragment.':'Enable a source in Settings, then explicitly capture content on its webpage.'}</EmptyDescription></EmptyHeader><EmptyContent><Button variant="outline" onClick={()=>query?setQuery(''):setDialog('settings')}>{query?'Clear search':'Open settings'}</Button></EmptyContent></Empty>}
      <footer className="list-footer">{scenario==='loading'?'Reading local capture summaries…':'Local retention and Locus saving are separate.'}</footer></section>
      <section className="inspector" aria-label="Capture inspection">{sample?<><header className="inspector-header"><div className="source-line"><span>{sample.site} · Captured {sample.age}</span><a href={sample.url} target="_blank" rel="noreferrer">Open source<ArrowUpRightIcon aria-hidden="true"/></a></div><div className="record-heading"><h2>{sample.label}</h2><div className="inspector-actions"><Button className="back-button" ref={backRef} variant="outline" onClick={back}><ArrowLeftIcon aria-hidden="true" data-icon="inline-start"/>Back</Button><Button variant="outline" disabled={sample.id==='active'} onClick={()=>feedback('Export is illustrated here; no file was downloaded.')}><DownloadIcon aria-hidden="true" data-icon="inline-start"/>{sample.id==='partial'?'Export available':'Export ZIP'}</Button><Button variant="ghost" size="icon-lg" aria-label="Clear result" onClick={()=>setDialog('clear')}><Trash2Icon/></Button></div></div><Outcomes sample={sample}/><div className="next-action"><div><strong>{sample.headline}</strong><p>{sample.reason}</p></div>{sample.action&&<Button onClick={action}>{sample.action}<ArrowUpRightIcon aria-hidden="true" data-icon="inline-end"/></Button>}</div></header>
        <Tabs value={tab} onValueChange={value=>setTab(String(value))} className="detail-tabs"><TabsList variant="line" aria-label="Capture details"><TabsTrigger value="preview">Preview</TabsTrigger><TabsTrigger value="metadata">Metadata</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger></TabsList><TabsContent value="preview" className="detail-content"><div className="author-line"><div className="author-avatar" aria-hidden="true">{sample.author.split(' ').map(w=>w[0]).join('').slice(0,2)}</div><div><strong>{sample.author}</strong><small>{sample.handle} · Source content</small></div></div><article className="captured-text">{sample.text}</article><div className="files-heading"><h3>Selected files</h3><span>{sample.id==='partial'?'One selected file unavailable':sample.site==='Bilibili'?'Video sample':'Text-only capture'}</span></div><div className="file-row"><FileIcon aria-hidden="true"/><div><strong>{sample.id==='partial'?'Selected image unavailable':sample.site==='Bilibili'?'Selected video part':'Message and metadata'}</strong><p>{sample.id==='partial'?'Source request failed. Available message content remains inspectable and exportable.':sample.site==='Bilibili'?'The design sample illustrates file state without loading or acquiring real media.':'No media files were selected; no files are missing.'}</p></div></div></TabsContent>
        <TabsContent value="metadata" className="detail-content"><dl className="metadata"><dt>Source</dt><dd>{sample.site}</dd><dt>Label</dt><dd>{sample.label}</dd><dt>Source URL</dt><dd>{sample.url}</dd><dt>Selection</dt><dd>{sample.id==='partial'?'Message and one image':sample.site==='Bilibili'?'Selected video part':'Message only'}</dd><dt>Local copy</dt><dd>{sample.local.text}</dd><dt>Locus save</dt><dd>{sample.locus.text}</dd></dl></TabsContent>
        <TabsContent value="activity" className="detail-content"><div className="activity-block"><h3>What happens next</h3><Alert variant={sample.id==='failed'||sample.id==='retention'?'destructive':'default'}><ShieldCheckIcon aria-hidden="true"/><AlertTitle>{sample.headline}</AlertTitle><AlertDescription>{sample.reason}</AlertDescription></Alert>{['failed','unverified'].includes(sample.id)&&<><Button className="self-start" onClick={()=>feedback('The original-save control is illustrated; no request was sent.')}>Check and continue original save</Button><p className="sample-dialog-description">This action checks the existing attempt. It does not create another capture or repeat confirmed uploads.</p></>}{sample.id==='setup'&&<Button className="self-start" onClick={()=>setDialog('settings')}>Connection settings</Button>}<details><summary>Technical details</summary><pre>Example result: {sample.id}{'\n'}Capture: {sample.capture.text}{'\n'}Local retention: {sample.local.text}{'\n'}Locus delivery: {sample.locus.text}{'\n'}Synthetic evidence only. No network operation occurred.</pre></details></div></TabsContent></Tabs></>:<Empty><EmptyHeader><EmptyMedia><ListIcon aria-hidden="true"/></EmptyMedia><EmptyTitle>Select a capture</EmptyTitle><EmptyDescription>Read the original content, see each outcome, and choose what happens next.</EmptyDescription></EmptyHeader></Empty>}</section>
    </main>}
    <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent className="max-h-[85svh] overflow-y-auto"><DialogHeader><DialogTitle>{dialog==='settings'?'Connection settings':dialog==='queue'?'Task queue':dialog==='clear'?'Clear this local result?':'Library navigation'}</DialogTitle><DialogDescription>{dialog==='clear'?`${sample?.label}. Only the extension’s local copy is removed. Exports and accepted Locus content remain.`:dialog==='navigation'?'Choose the capture view.':'Synthetic design sample. No settings, permissions or network requests are changed.'}</DialogDescription></DialogHeader>
      {dialog==='settings'&&<FieldGroup><Field><FieldLabel htmlFor="example-address">Locus address</FieldLabel><Input id="example-address" readOnly value="http://127.0.0.1:46321"/><FieldDescription>Example address only. Set up the real connection in the production extension.</FieldDescription></Field><Field><FieldLabel htmlFor="example-token">Token</FieldLabel><Input id="example-token" readOnly value="No real credentials in this sample"/><FieldDescription>Connection setup does not automatically send older captures.</FieldDescription></Field></FieldGroup>}
      {dialog==='queue'&&<><div className="queue-row"><div className="flex items-center justify-between gap-2"><strong>Quiet workshop · P2</strong><Status value={{text:"Acquiring",tone:"info"}}/></div><progress max="100" value="64" aria-label="Synthetic acquisition progress"/><span className="sample-dialog-description">64% in this static example · producer-reported progress</span></div><div className="queue-row"><strong>Morning walk notes</strong><Status value={{text:"Staged locally",tone:"outline"}}/><span className="sample-dialog-description">Configure Locus, then explicitly continue the original save.</span></div><p className="sample-dialog-description">Closing the queue does not cancel accepted captures.</p></>}
      {dialog==='navigation'&&<div className="navigation-dialog">{navigation()}</div>}
      <DialogFooter><Button variant="outline" onClick={()=>setDialog(null)}>{dialog==='clear'?'Cancel':'Close'}</Button>{dialog==='clear'&&<Button variant="destructive" onClick={()=>{if(selected)setRemoved(old=>[...old,selected]);setDialog(null);setSelected(null);feedback('Only this synthetic row was removed. Reset the example to restore it.');}}>Clear sample result</Button>}{dialog==='settings'&&<Button disabled>Connect and save</Button>}</DialogFooter></DialogContent></Dialog>
    {notice&&<div className="sample-toast" role="status"><span>{notice}</span><Button variant="ghost" size="icon" aria-label="Dismiss sample notice" onClick={()=>setNotice('')}><XIcon/></Button></div>}
  </>;
}

function ComponentSheet({onSettings,onQueue,onFeedback}:{onSettings:()=>void;onQueue:()=>void;onFeedback:(text:string)=>void}) {
  const swatches=['sidebar','background','card','primary','foreground','muted-foreground'];
  return <main className="specimen"><h1>Signal shelf, across the extension</h1><p className="specimen-intro">A blue working environment, a crisp type scale, and a parallel vocabulary for capture outcomes. These are rendered examples of the proposed system, using the project’s installed primitives.</p>
    <section className="specimen-section"><h2>Color roles</h2><div className="swatches">{swatches.map(token=><div key={token}><div className="swatch" style={{background:`var(--${token})`}}/><strong>{token}</strong><div className="swatch-label">Dark-only semantic role</div></div>)}</div></section>
    <section className="specimen-section"><h2>Actions, with one clear priority</h2><div className="specimen-line"><Button onClick={onSettings}>Connection settings</Button><Button variant="outline" onClick={()=>onFeedback('Export action example; no download started.')}><DownloadIcon aria-hidden="true" data-icon="inline-start"/>Export ZIP</Button><Button variant="secondary" onClick={onQueue}>Task queue</Button><Button variant="ghost" onClick={()=>onFeedback('Context action example.')}>View details</Button><Button variant="destructive" onClick={()=>onFeedback('Destructive treatment example; nothing removed.')}>Clear result</Button><Button disabled>Saving…</Button></div></section>
    <section className="specimen-section"><h2>State is a word, an icon and a color</h2><div className="specimen-line">{[{text:'Staged locally',tone:'outline'},{text:'Saved to Locus',tone:'success'},{text:'Save failed',tone:'destructive'},{text:'Partial capture',tone:'warning'},{text:'Acquiring',tone:'info'}].map(value=><Status key={value.text} value={value as Outcome}/>)}</div><p>Neutral staging never borrows the error treatment. Local retention does not stand in for a confirmed Locus save.</p><Outcomes sample={samples[5]!}/></section>
    <section className="specimen-section"><h2>Typography and reading</h2><h3 className="text-lg font-semibold">Selected capture · 18px</h3><p className="captured-text">The useful context stays close to the content. Read what you captured, understand what is safe, and choose the next action with confidence.</p><p>UI text uses 14px, metadata 12px, section titles 18px, workspace titles 24px. Captured prose uses 16px with a 1.75 line height and a 68-character maximum measure.</p></section>
    <section className="specimen-section"><h2>Feedback stays actionable</h2><Alert variant="destructive"><CircleAlertIcon aria-hidden="true"/><AlertTitle>Current content is not retained locally</AlertTitle><AlertDescription>Only committed content is recoverable after restart. Export available content if you need a local copy.</AlertDescription></Alert><div className="specimen-line mt-4"><Button variant="outline" onClick={onSettings}>Preview settings</Button><Button variant="outline" onClick={onQueue}>Preview queue</Button></div></section>
    <section className="specimen-section"><h2>Source-page controls</h2><div className="specimen-line"><Button aria-label="Capture selected content" size="icon-lg" onClick={()=>onFeedback('Page capture control illustrated; no content acquired.')}><DownloadIcon/></Button><Button variant="secondary" onClick={onQueue}><LayersIcon aria-hidden="true" data-icon="inline-start"/>1 task</Button><Status value={{text:"Staged locally",tone:"outline"}}/></div><p>Carry the same icons and outcome language into webpage controls. Preserve each host site’s native placement and keep capture explicitly user initiated.</p></section>
  </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
